[Http-Requests 2018-09-12 11:30:43,508 HTTP_requests.py HTTP_requests  INFO] ===》 获取接口地址成功：ht[damao 2018-09-12 11:30:45,695 test_my_demo.py test_my_demo  INFO] ===》 请求体参数：params:{'c': 1}
[damao 2018-09-12 11[Http-Requests 2018-09-12 11:30:45,711 HTTP_requests.py HTTP_requests  INFO] ===》 获取接口地址成功：http://httpbin.org/
[Http-Requests 2018-09-12 11:30:46,260 HTTP_requests.py HTTP_requests  INFO] ===》 get请求发送成功！
ate', 'Accept': '*/*', 'Connection': 'keep-alive'}
[damao 2018-09-1[python 2018-09-12 11:30:50,683 run.py run  INFO] ===》 邮件发送成功！
[python 2018-09-12 11:30:50,683 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-18-02-12-47.log' already exists
[python 2018-09-12 11:30:50,683 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-18-02-14-21.log' already exists
[python 2018-09-12 11:30:50,683 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-18-02-19-01.log' already exists
[python 2018-09-12 11:30:50,683 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-18-02-19-02.log' already exists
[python 2018-09-12 11:30:50,683 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-24-15-47-16.log' already exists
[python 2018-09-12 11:30:50,683 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-31-18-23-18.log' already exists
[python 2018-09-12 11:30:50,683 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-08-31-18-23-19.log' already exists
[python 2018-09-12 11:30:50,683 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-09-01-11-21-36.log' already exists
[python 2018-09-12 11:30:50,683 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-09-10-09-34-49.log' already exists
[python 2018-09-12 11:30:50,683 run.py run  INFO] ===》 剪切失败：Destination path '.\logs\zip_log\auto_test_2018-09-12-10-17-45.log' already exists
